# -*- coding: utf-8 -*-
"""Frame_IP_30-01-24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JY8CE5iURK7K1Z-3CH7R2zH-x9XGCGk9
"""

# Importa as bibliotecas necessárias
import pandas as pd                 # Importa a biblioteca Pandas para manipulação de dados (Planilha Excel)
import matplotlib.pyplot as plt     # Importa a biblioteca Matplotlib para plotagem de gráficos
from datetime import datetime       # Importa o módulo datetime para trabalhar com datas e horários

# Função para converter a coluna 'Time' para o formato de segundos com 5 casas decimais
def convert_to_seconds(time_str):
    # Converte uma string de data e hora em um objeto de data e hora e obtém o timestamp
    timestamp = datetime.strptime(time_str, '%Y-%m-%d %H:%M:%S.%f').timestamp()
    return round(timestamp, 5)  # Arredonda para 5 casas decimais

# Carregar o arquivo Excel
file_path = '/content/gamebox5g2_12_01_24_completo.xlsx'  # Substitua pelo caminho do seu arquivo

# Inicializa a variável 'dados' como None
dados = None

# Tenta ler o arquivo Excel
try:
    dados = pd.read_excel(file_path)
except FileNotFoundError:
    print('ERRO: Arquivo não encontrado. Verifique o caminho do arquivo.')
    exit()

# Verifica se a variável 'dados' foi definida
if dados is not None:
    # Converte a coluna 'Time' para segundos com 5 casas decimais
    dados['Time'] = dados['Time'].astype('str')     # Converte a coluna 'Time' para o tipo string
    dados['Time'] = dados['Time'].apply(convert_to_seconds)  # Aplica a função convert_to_seconds à coluna 'Time'

    # Filtra para download (DL)
    dl_data = dados[(dados['Destination'] == '10.215.173.1') & (dados['Source'] == '211.252.120.14')]
    dl_frames = dl_data[['Time', 'Length']].copy()  # Seleciona as colunas 'Time' e 'Length' para DL
    dl_frames.rename(columns={'Length': 'Frame DL (bytes)'}, inplace=True)  # Renomeia a coluna 'Length'

    # Filtra para upload (UL)
    ul_data = dados[(dados['Source'] == '10.215.173.1') & (dados['Destination'] == '211.252.120.14')]
    ul_frames = ul_data[['Time', 'Length']].copy()  # Seleciona as colunas 'Time' e 'Length' para UL
    ul_frames.rename(columns={'Length': 'Frame UL (bytes)'}, inplace=True)  # Renomeia a coluna 'Length'

    # Filtra IP de Origem e Destino
    ip_data = dados[['Time', 'Source', 'Destination']].copy()

    # Determina o número total de linhas
    num_linhas = min(len(dl_frames), len(ul_frames), len(ip_data))

    # Exibir as tabelas de frames e IP de origem e destino linha a linha
    for i in range(num_linhas):
        print("\nLinha", i + 1)
        print("Tabela de Frames de Download (DL):")
        print(dl_frames.iloc[i])

        print("Tabela de Frames de Upload (UL):")
        print(ul_frames.iloc[i])

        print("Tabela de IP de Origem e Destino:")
        print(ip_data.iloc[i])

print(len(ip_data))